sudo: required
services:
  - docker

before_install:
  - docker build -t jhuang71/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true jhuang71/react-test npm test

after_success:
  - docker build -t jhuang71/multi-client ./client
  - docker build -t jhuang71/multi-nginx ./nginx
  - docker build -t jhuang71/multi-server ./server
  - docker build -t jhuang71/multi-worker ./worker
  #Log in to the Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those image and push it to docker hub
  - docker push jhuang71/multi-client
  - docker push jhuang71/multi-nginx
  - docker push jhuang71/multi-server
  - docker push jhuang71/multi-worker
